In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

In [4]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600
...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [5]:
print(df.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [9]:
avg_open = df['Open'].mean()
avg_close = df['Close'].mean()

print(f"Average Open Price:  ${avg_open:.2f}")
print(f"Average Close Price: ${avg_close:.2f}")

Average Open Price:  $127.04
Average Close Price: $127.35

In [13]:
df = df.sort_values(by='Date')
df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Change,Daily_Change_Pct,Day_To_Day_Change_Pct
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700,-0.969993,-0.964304,NaN
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200,0.780006,0.780396,1.114234
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800,-3.660004,-3.611965,-3.037829
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900,6.900001,7.017902,7.730115
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600,3.150002,3.004294,2.642082
...,...,...,...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700,4.769989,2.722441,2.139486
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500,-2.269989,-1.259077,-1.089005
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700,-12.380005,-6.981730,-7.347490
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400,-0.290008,-0.172552,1.721836
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505,-0.024994,-0.014895,0.000000

In [15]:
df['Daily Delta'] = df['Close'] - df['Open']

In [16]:
df['Daily Return'] = (
    (df['Close'] - df['Open'])/ df['Open']
    )*100